Repository GSG-G11/UniFinder-project-team-1, pull requests merged in 2022-02, with the labels that each got.

#3 Update Readme File
  .gitignore
  README.md
Labels: Done

#5 Create File Structure
  css/style.css
  index.html
  js/app.js
  js/dom.js
  js/fetch.js
  search.html
Labels: Done

#8 Fix File structure and add info.html then add to Folder html
  css/info.css
  html/info.html
  html/search.html
  index.html
Labels: Awaiting Review

#12 Create Nav Bar Section As html and css ,
  css/style.css
  html/search.html
  images/bar.svg
  js/app.js
  js/dom.js
Labels: Done

#13 Create Landing Page using HTML and CSS
  css/style.css
  images/welcomeImage.svg
  index.html
Labels: Awaiting Review

#15 Create Universities section in info page
  css/info.css
  css/style.css
  html/info.html
  html/search.html
Labels: Awaiting Review

#16 Create body search html css
  css/style.css
  html/search.html
  images/Search_Background.svg
  images/egypt.jpg
  images/emirate.jpg
  images/italy.jpg
  images/lebanon.jpg
  images/spain.jpg
  images/turkey.jpg
  js/dom.js
Labels: Approved

#26 Add animations for SVG and for the first render
  css/style.css
  html/search.html
  index.html
Labels: Approved

#28 Refactor DOM Functions
  css/info.css
  html/info.html
  js/dom.js
Labels: Awaiting Review

#30 Edit fetch function and add error page
  css/style.css
  html/error.html
  js/dom.js
  js/fetch.js
Labels: Awaiting Review

#32 Make info page responsive
  css/info.css
  html/error.html
  index.html
  js/dom.js
Labels: Approved

#34 Fetch general information from the first API
  css/style.css
  html/error.html
  html/info.html
  html/search.html
  index.html
  js/app.js
  js/dom.js
  js/info.js
Labels: Awaiting Review

#36 Create Function to the most popular countries
  html/search.html
  js/app.js
Labels: Approved

#37 Edit click event in addListener function
  js/app.js
Labels: Approved

#39 Create Fetch Universities Function
  js/app.js
  js/info.js
Labels: Approved

#41 Edit responsive in info page
  css/info.css
  html/info.html
Labels: Approved

#43 Add Animation to info page
  css/info.css
  html/info.html
Labels: Approved

#45 Edit error in info script
  js/info.js
Labels: Approved

#47 Handing Error Page after request
  html/search.html
  js/app.js
Labels: Awaiting Review

#49 Add favicon website logo
  html/error.html
  html/info.html
  html/search.html
  images/favicon.ico
  index.html
Labels: Approved

#53 Fix Issues
  js/dom.js
  js/fetch.js
  js/info.js
Labels: Approved
